### ISSUE TITLE
Occasional scroll glitching on iOS

### ISSUE THREAD

**Issue by adammcarth** [adammcarth/react-native-segmented-picker#1]
This package was made initially for Android, so I must point out that some of the scrolling subtleties/performance issues on iOS have not yet been fully ironed out. The scrolling just feels a little bit dodgy on iOS still compared to Android. It definitely works - but it's fairly easy to break if you scroll fast or try to trick it.

I've found that the key difference between Android and iOS is that you can always rely on <ScrollView />'s `onMomentumScrollBegin|End` to fire after any scrolling takes place on Android. It's a really reliable method to determine when someone is interacting with the scroll view or not. However - iOS fires this event far less consistently. Instead we need to use the `onScrollBeginDrag|End` methods to auto-select positions in the list after a user raises their finger.

Another iOS bug I've found is that if you scroll down to the very bottom of a list and keep scrolling (whilst holding the gravity), you can get the wheel into a position that's totally off the list.

In light of all that, there's definitely a little bit of fine tuning required. Good first issue if anyone wants to help.

**Comment by marcocavanna** [comment]
While not using native picker on iOS wrapped into your component?

**Comment by adammcarth** [comment]
@marcocavanna One of the central goals for this project is for it to always work without the overhead of leveraging native code. I want it to be lean and approachable for people who are new to React Native, and also people that use frameworks like [Expo](https://expo.io) (where module linking is not possible).

That said, I'm _definitely_ open to offering the Native iOS Picker to be toggled programatically though. Perhaps something like:

```javascript
<SegmentedPicker
  iOSNativeEnabled
  options={{ ... }}
  ...
/>
```

To my knowledge... that module would it would have to be written from scratch for this project though. One of the pitfalls of all the other [picker components](https://github.com/react-native-community/react-native-picker) out there is that they don't support multiple columns (besides `react-native-date-picker`).

Something to put on the roadmap I reckon!

**Comment by adammcarth** [comment]
Note that the scrolling behaviour has been changed for iOS slightly in `v1.1.1`. This improves the scrolling to make it more realistic - but I've still seen it glitch out occasionally still if you push it with the scrolling up and down.

**Comment by adammcarth** [comment]
These issues have been address in `v2.0.0`.
