### ISSUE TITLE
native pod install error (IOS)

### ISSUE THREAD

**Issue by greenglobaltr** [adammcarth/react-native-segmented-picker#35]
When i try to 'pod install' i am getting this error.

Installing RNSegmentedPicker (2.0.2)

[!] Error installing RNSegmentedPicker
[!] /usr/local/bin/git clone git+https://github.com/adammcarth/react-native-segmented-picker.git /var/folders/ct/v1xh12996pj13djk0jbh5fn80000gn/T/d20210121-97138-3di43f --template= --single-branch --depth 1 --branch v2.0.2

Cloning into '/var/folders/ct/v1xh12996pj13djk0jbh5fn80000gn/T/d20210121-97138-3di43f'...
fatal: unable to find remote helper for 'git+https'

**Comment by adammcarth** [comment]
Hey @greenglobaltr :)

As far as I can tell, this sounds like a local issue. A quick google suggested [this might fix it](https://github.com/gatsbyjs/gatsby/issues/3874#issuecomment-363400695) for you? But that's definitely weird... I've never seen that error in any context before.

Out of interest, what's are your versions for?:

- OSX
- Git
- Cocoapods
