### ISSUE TITLE
Is it possible to remove or to customise the upper toolbar?

### ISSUE THREAD

**Issue by vladiRozen** [adammcarth/react-native-segmented-picker#39]
Is it possible to remove or to customise the upper toolbar 
/ or to use only the pickers without the modal?

**Comment by adammcarth** [comment]
Hey @vladiRozen! Sorry for the late reply - I was on vacation when you posted this.

There are some [small customisations](https://github.com/adammcarth/react-native-segmented-picker#props) you can make to the colouring of the upper toolbar:

- `confirmText`
- `confirmTextColor`
- `toolbarBackgroundColor`
- `toolbarBorderColor`

That doesn't allow you to hide it or change the sizing though.

There's an [existing feature request](https://github.com/adammcarth/react-native-segmented-picker/issues/22) (which will be addressed in a future update) where you can use the raw picklist component without having to present it in the modal. That will require a bit of re-working and I don't have a time frame on that just yet.
