### ISSUE TITLE
Question: Can I populate the second column only when the first column is selected?

### ISSUE THREAD

**Issue by joshuapinter** [adammcarth/react-native-segmented-picker#5]
Looks great, thanks!

**Comment by adammcarth** [comment]
Hey mate.

Yeah! So we're doing that exact same thing internally, you just need to use the [`onValueChange`](https://github.com/adammcarth/react-native-segmented-picker#event-props) prop to update the second column. A flow like this perhaps:

```js
import React, { Component } from 'react';
import SegmentedPicker from 'react-native-segmented-picker';

const options = {
  categories: [{ label: 'Fruits' }, { label: 'Vegetables' }],
  items: {
    Fruits: [{ label: 'Apples' }, { label: 'Oranges' }],
    Vegetables: [{ label: 'Carrots' }, { label: 'Potatoes' }],
  },
};

class Demo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selections: {
        categories: options.categories[0],
        items: undefined,
      },
    };
  }

  onValueChange = (columnId, { label }) => {
    this.setState((prevState) => ({
      selections: {
        ...prevState.selections,
        [columnId]: label,
      },
    }));
  };

  generateOptions = () => {
    const { categories, items } = options;
    const { selections } = this.state;
    return {
      categories,
      items: items[selections.categories],
    };
  };

  render() {
    const { selections: { categories, items } } = this.state;
    return (
      <SegmentedPicker
        options={this.generateOptions()}
        onValueChange={this.onValueChange}
        defaultSelections={{ categories, items }}
      />
    );
  }
}
```

Does that make sense?

I might add it to a new "Recipes" section of the README or something. Dare say it'll be a pretty common use case.

**Comment by adammcarth** [comment]
Oh... and if you want the second column literally blank to start with? There's actually a few different implementation options there I think. One way is to have a blank option in the first column and set the second column to an empty array initially?

**Comment by joshuapinter** [comment]
Beauty! Thanks for the quick response. Was thinking of a similar implementation. I definitely think it would be a worthy addition to the README. Thanks again.
