### ISSUE TITLE
how to open picker with desired value?

### ISSUE THREAD

**Issue by creativemind1** [adammcarth/react-native-segmented-picker#62]
I'm opening picker with `Ref.current.show()` I want my picker to scroll to the value I want. How can I do this?

**Comment by adammcarth** [comment]
There's a prop called `defaultSelections` where you can pass in an object with the key of a column mapped to a value that you want automatically selected when the picker opens. Note that it won't animate/visibly scroll to the default selection, however. It will snap to it without an animation.

**Comment by creativemind1** [comment]
Thanks
