### ISSUE TITLE
Unhandled Promise Rejection while using `visible`

### ISSUE THREAD

**Issue by marcocavanna** [adammcarth/react-native-segmented-picker#7]
Hi,

there is a small using when using the component through `visible` props.

While hiding the backdrop the instruction
```js
await this.pickerContainerRef.current.fadeOut(this.animationTime)
```

throw an error because the `modalContainerRef.current` is null.

I suggest to put this into a try catch statement.

Using `visible` props is mandatory for me because using ref function (show, hide) produce a glitch when component will fade out...

**Comment by adammcarth** [comment]
Hey @marcocavanna. Thanks for reporting this - I'm taking a look into it now.

I first noticed that fade-out glitch recently too, but only on iOS. Have you been testing on Android and iOS, or just one of those platforms?

**Comment by adammcarth** [comment]
@marcocavanna Can you please confirm this is fixed in `v.1.1.0`? Cheers!

**Comment by adammcarth** [comment]
@marcocavanna Damn. I still get occasional glitches when closing the picker on my iPhone XS! I think I might open a separate issue for this :(

**Comment by marcocavanna** [comment]
I don't know if problem is here, but as the `fadeOut` is a Promise, personally I prefer waiting for enable animation end before setting visible to false.

So, instead writing:

```js
this.modalContainerRef.current.fadeOut(ANIMATION_TIME);
await this.pickerContainerRef.current.fadeOut(ANIMATION_TIME);
this.setState({ visible: false }, () => {
    this.cache.purge();
});
```

You probably could be more consistent and avoid any error writing
```js
await Promise.all([
  /** Hide Modal Container */
  new Promise((resolve) => {
    if (this.modalContainerRef.current?.fadeOut) {
      return this.modalContainerRef.current.fadeOut(ANIMATION_TIME).then(resolve);
    }
    return resolve();
  }),

  /** Hide Picker Container */
  new Promise((resolve) => {
    if (this.pickerContainerRef.current?.fadeOut) {
      return this.pickerContainerRef.current.fadeOut(ANIMATION_TIME).then(resolve);
    }
    return resolve();
  }),
]);

this.setState({ visible: false }, () => {
  this.cache.purge();
});
```
